- name: copy systemd unit
  ansible.builtin.template:
    src: verwaltungsportalsql.service.j2
    dest: /etc/systemd/system/verwaltungsportalsql.service
    owner: root
    group: root
    mode: '644'
  notify: restart verwaltungsportalsql.service

- name: create verwaltungsportalsql/data dir
  ansible.builtin.file:
    path: '{{ root }}/data'
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ root }}/docker-compose.yml'
    owner: root
    group: root
    mode: '644'
  notify: restart verwaltungsportalsql.service

- name: start verwaltungsportalsql.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: verwaltungsportalsql.service
  register: verwaltungsportalsql_started
