- name: copy systemd unit
  ansible.builtin.template:
    src: filteredrapla.service.j2
    dest: /etc/systemd/system/filteredrapla.service
    owner: root
    group: root
    mode: '644'
  notify: restart filteredrapla.service

- name: create /data/filteredrapla dir
  ansible.builtin.file:
    path: '{{ root }}'
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ root }}/docker-compose.yml'
    owner: root
    group: root
    mode: '644'
  notify: restart filteredrapla.service

- name: start filteredrapla.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: filteredrapla.service
  register: filteredrapla_started
