- name: copy systemd unit
  ansible.builtin.template:
    src: netdata.service.j2
    dest: /etc/systemd/system/netdata.service
    owner: root
    group: root
    mode: "644"
  notify: restart netdata.service

- name: create /data/netdata/config dir
  ansible.builtin.file:
    path: "{{ root }}/config"
    state: directory

- name: create /data/netdata/lib dir
  ansible.builtin.file:
    path: "{{ root }}/lib"
    state: directory

- name: create /data/netdata/cache dir
  ansible.builtin.file:
    path: "{{ root }}/cache"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart netdata.service

- name: start netdata.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: netdata.service
  register: netdata_started
