- name: copy systemd unit
  ansible.builtin.template:
    src: mc.service.j2
    dest: /etc/systemd/system/mc.service
    owner: root
    group: root
    mode: '644'
  notify: restart mc.service

- name: create /data/mc dir
  ansible.builtin.file:
    path: '{{ root }}'
    state: directory

- name: create /data/mc/data dir
  ansible.builtin.file:
    path: '{{ root }}/data'
    state: directory

- name: create /data/mc/backup dir
  ansible.builtin.file:
    path: '{{ root }}/backup'
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ root }}/docker-compose.yml'
    owner: root
    group: root
    mode: '644'
  notify: restart mc.service

- name: start mc.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: mc.service
  register: mc_started
