- name: copy systemd unit
  ansible.builtin.template:
    src: webspace.service.j2
    dest: /etc/systemd/system/webspace.service
    owner: root
    group: root
    mode: "644"
  notify: restart webspace.service

- name: create /data/webspace dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: create /data/webspace/data dir
  ansible.builtin.file:
    path: "{{ root }}/data"
    state: directory

- name: copy nginx conf file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ root }}/nginx.conf"
    owner: root
    group: root
    mode: "644"
  notify: restart webspace.service

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart webspace.service

- name: start webspace.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: webspace.service
  register: webspace_started
