- name: copy systemd unit
  ansible.builtin.template:
    src: mySQLDatabase.service.j2
    dest: /etc/systemd/system/mySQLDatabase.service
    owner: root
    group: root
    mode: '644'
  notify: restart mySQLDatabase.service

- name: create mySQLDatabase/data dir
  ansible.builtin.file:
    path: '{{ root }}/data'
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ root }}/docker-compose.yml'
    owner: root
    group: root
    mode: '644'
  notify: restart mySQLDatabase.service

- name: start mySQLDatabase.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: mySQLDatabase.service
  register: mySQLDatabase_started
