- name: copy systemd unit
  ansible.builtin.template:
    src: retrogames.service.j2
    dest: /etc/systemd/system/retrogames.service
    owner: root
    group: root
    mode: "644"
  notify: restart retrogames.service

- name: create /data/retrogames/config dir
  ansible.builtin.file:
    path: "{{ root }}/config"
    state: directory

- name: create /data/retrogames/data dir
  ansible.builtin.file:
    path: "{{ root }}/data"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart retrogames.service

- name: start retrogames.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: retrogames.service
  register: retrogames_started
